//#############
// This file or equiv was possibly autogenerated for STM32VL BOARD but was not
// autogenerated for the stmcube with just the STM32F100RBTx
// Since we still wanted to blink the LED's it was hand inserted,
// into the I2C_100Khz and I2C_Uart_WithInterupts projects.
//#############
/*
 * led.h
 *
 *  Created on: Oct 2, 2017
 *      Author: jmk
 */

#ifndef LED_H_
#define LED_H_

/* Includes ------------------------------------------------------------------*/
#define LD4_Blue_Pin GPIO_PIN_8
#define LD4_Blue_GPIO_Port GPIOC
#define LD3_Green_Pin GPIO_PIN_9
#define LD3_Green_GPIO_Port GPIOC

#define BlueButton_Pin GPIO_PIN_0
#define BlueButton_GPIO_Port GPIOA


#define LEDn   			2
#define BUTTONn			1

typedef enum
{
  LED3 = 0,
  LED4 = 1
} Led_TypeDef;

typedef enum
{
  BUTTON_USER = 0
} Button_TypeDef;

typedef enum
{
  BUTTON_MODE_GPIO = 0,
  BUTTON_MODE_EXTI = 1
} ButtonMode_TypeDef;


/* Function Prototypes: */
void STM32vldisc_LEDOn(Led_TypeDef Led);
void STM32vldisc_LEDOff(Led_TypeDef Led);
void STM32vldisc_LEDToggle(Led_TypeDef Led);
uint32_t STM32vldisc_PBGetState(Button_TypeDef Button);

#endif /* LED_H_ */
